import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'shastra-001',
    name: 'The Visionary',
    brand: 'Aurum',
    price: 4999.00,
    style: 'classic',
    material: 'acetate',
    images: ['https://picsum.photos/800/600?random=1', 'https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=3'],
    description: 'A timeless design that blends classic aesthetics with contemporary comfort. The Visionary is perfect for those who appreciate understated elegance.',
    specs: {
      frameWidth: '140mm',
      lensWidth: '50mm',
      lensHeight: '42mm',
      bridge: '20mm',
      armLength: '145mm',
    },
    reviews: [
      { id: 1, author: 'Aarav D.', rating: 5, text: 'Absolutely love these glasses! They fit perfectly and feel very high quality.' },
      { id: 2, author: 'Mira S.', rating: 4, text: 'Great style and very comfortable for all-day wear.' },
    ],
  },
  {
    id: 'shastra-002',
    name: 'Aero-Flex',
    brand: 'Zenith',
    price: 7499.00,
    style: 'aviator',
    material: 'titanium',
    images: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=5', 'https://picsum.photos/800/600?random=6'],
    description: 'Engineered for performance and style, the Aero-Flex features an ultra-lightweight titanium frame and a modern aviator silhouette.',
    specs: {
      frameWidth: '145mm',
      lensWidth: '58mm',
      lensHeight: '48mm',
      bridge: '17mm',
      armLength: '150mm',
    },
    reviews: [
      { id: 1, author: 'Rohan P.', rating: 5, text: 'So light I forget I\'m wearing them. The quality is exceptional.' },
    ],
  },
  {
    id: 'shastra-003',
    name: 'The Scholar',
    brand: 'Cognita',
    price: 3999.00,
    style: 'vintage',
    material: 'metal',
    images: ['https://picsum.photos/800/600?random=7', 'https://picsum.photos/800/600?random=8', 'https://picsum.photos/800/600?random=9'],
    description: 'Inspired by mid-century academia, The Scholar features a rounded metal frame that exudes intelligence and charm.',
    specs: {
      frameWidth: '135mm',
      lensWidth: '48mm',
      lensHeight: '45mm',
      bridge: '21mm',
      armLength: '140mm',
    },
    reviews: [
      { id: 1, author: 'Priya R.', rating: 5, text: 'The perfect vintage look I was searching for. Compliments everywhere I go!' },
      { id: 2, author: 'Ben Carter', rating: 5, text: 'Sturdy, stylish, and comfortable. An excellent pair of glasses.' },
    ],
  },
  {
    id: 'shastra-004',
    name: 'Urbanite',
    brand: 'Metropolis',
    price: 5999.00,
    style: 'modern',
    material: 'acetate',
    images: ['https://picsum.photos/800/600?random=10', 'https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
    description: 'Sleek, bold, and unapologetically modern. The Urbanite\'s sharp lines and durable acetate construction are made for the city.',
    specs: {
      frameWidth: '142mm',
      lensWidth: '52mm',
      lensHeight: '40mm',
      bridge: '19mm',
      armLength: '148mm',
    },
    reviews: [
      { id: 1, author: 'Chloe T.', rating: 4, text: 'Very stylish and they make a statement. A bit heavier than my last pair but I got used to it.' },
    ],
  },
  {
    id: 'shastra-005',
    name: 'The Naturalist',
    brand: 'Arbor',
    price: 8999.00,
    style: 'classic',
    material: 'wood',
    images: ['https://picsum.photos/800/600?random=13', 'https://picsum.photos/800/600?random=14', 'https://picsum.photos/800/600?random=15'],
    description: 'Crafted from sustainably sourced wood, The Naturalist offers a unique, organic aesthetic that connects you with nature.',
    specs: {
      frameWidth: '138mm',
      lensWidth: '49mm',
      lensHeight: '43mm',
      bridge: '22mm',
      armLength: '145mm',
    },
    reviews: [
        { id: 1, author: 'Liam G.', rating: 5, text: 'Beautiful craftsmanship. Each pair is unique, and they are surprisingly comfortable.' },
    ],
  },
  {
    id: 'shastra-006',
    name: 'Stealth',
    brand: 'Zenith',
    price: 9999.00,
    style: 'modern',
    material: 'titanium',
    images: ['https://picsum.photos/800/600?random=16', 'https://picsum.photos/800/600?random=17', 'https://picsum.photos/800/600?random=18'],
    description: 'The epitome of minimalist design. Stealth combines a feather-light titanium frame with a rimless construction for a barely-there feel.',
    specs: {
      frameWidth: '136mm',
      lensWidth: '51mm',
      lensHeight: '38mm',
      bridge: '18mm',
      armLength: '145mm',
    },
    reviews: [
      { id: 1, author: 'Olivia W.', rating: 5, text: 'Incredibly lightweight and elegant. The best glasses I have ever owned.' },
      { id: 2, author: 'David L.', rating: 5, text: 'Worth every penny. The quality and comfort are unmatched.' },
    ],
  },
  {
    id: 'shastra-007',
    name: 'The Maverick',
    brand: 'Aurum',
    price: 6499.00,
    style: 'aviator',
    material: 'metal',
    images: ['https://picsum.photos/800/600?random=19', 'https://picsum.photos/800/600?random=20', 'https://picsum.photos/800/600?random=21'],
    description: 'A bold reinterpretation of the classic aviator. The Maverick features a distinctive double bridge and robust metal alloy construction.',
    specs: {
      frameWidth: '148mm',
      lensWidth: '60mm',
      lensHeight: '50mm',
      bridge: '16mm',
      armLength: '145mm',
    },
    reviews: [
        { id: 1, author: 'Sophia K.', rating: 5, text: 'I feel like a rockstar in these. They are so cool and surprisingly sturdy.' },
    ],
  },
  {
    id: 'shastra-008',
    name: 'The Curator',
    brand: 'Cognita',
    price: 4499.00,
    style: 'vintage',
    material: 'acetate',
    images: ['https://picsum.photos/800/600?random=22', 'https://picsum.photos/800/600?random=23', 'https://picsum.photos/800/600?random=24'],
    description: 'With its distinctive keyhole bridge and rich a cetate finish, The Curator is a tribute to vintage style and intellectual flair.',
    specs: {
      frameWidth: '139mm',
      lensWidth: '47mm',
      lensHeight: '44mm',
      bridge: '23mm',
      armLength: '142mm',
    },
    reviews: [
      { id: 1, author: 'Noah B.', rating: 5, text: 'Perfectly captures that vintage academic vibe. Very comfortable and well-made.' },
    ],
  },
];
